Temporarily undefine __ macro
This macro is used by tests as a shorthand for masm.; however, it
interferes with structured bindings in C++ headers, and causes the
following build error when upgrading Clang to r596125:

In file included from external/vixl/src/aarch64/simulator-aarch64.h:41:
In file included from external/vixl/src/aarch64/cpu-features-auditor-aarch64.h:36:
In file included from external/vixl/src/aarch64/decoder-aarch64.h:31:
In file included from prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/map:601:
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1146:13: error: expected unqualified-id
 1146 |     auto [__, __match] = __find_equal(__key);
      |             ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1146:24: error: expected unqualified-id
 1146 |     auto [__, __match] = __find_equal(__key);
      |                        ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1147:9: error: use of undeclared identifier '__match'; did you mean '__math'?
 1147 |     if (__match == nullptr)
      |         ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/math.h:386:11: note: '__math' declared here
  386 | namespace __math {
      |           ^
In file included from external/vixl/test/aarch64/test-assembler-aarch64.cc:39:
In file included from external/vixl/src/aarch64/cpu-aarch64.h:34:
In file included from external/vixl/src/aarch64/simulator-aarch64.h:41:
In file included from external/vixl/src/aarch64/cpu-features-auditor-aarch64.h:36:
In file included from external/vixl/src/aarch64/decoder-aarch64.h:31:
In file included from prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/map:601:
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1147:9: error: unexpected namespace name '__math': expected expression
 1147 |     if (__match == nullptr)
      |         ^
prebuilts/clang/host/linux-x86/clang-r596125/include/c++/v1/__tree:1149:55: error: use of undeclared identifier '__match'
 1149 |     return const_iterator(static_cast<__node_pointer>(__match));
      |                                                       ^~~~~~~
12 errors generated.

The same issue exists upstream, so upgrading the project doesn't
fix this. This CL fix provides a workaround so that the Clang update
can be unblocked. I'll file a bug upstream to get this fixed.

Bug: 472333761
Test: presubmit
Change-Id: I33682c63bb4e462a9eca3b3b4fa8c6ab46d2ceed